name = "lapce-pwsh"
display-name = "PowerShell"
description = "PowerShell for Lapce: powered by PowerShellEditorServices"
version = "0.0.1"
author = "panekj"
repository = "panekj/lapce-pwsh"
wasm = "lapce-pwsh.wasm"

[configuration]
system_lsp = true

[configuration.options.binary]
args = []
